import os
import shutil
from urllib.parse import urlparse
from fastapi import APIRouter, HTTPException, UploadFile, File
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from tavily import TavilyClient

from backend.agent.bot import chat_with_agent, stream_chat_with_agent
from backend.ingestion.pipeline import run_ingestion_pipeline
from dotenv import load_dotenv

load_dotenv()

router = APIRouter()

DATA_DIR = "d:\\AI_ENGINE\\PYTHON\\RAG\\PROJECTS\\customer-support-agent\\backend\\data"

class ChatRequest(BaseModel):
    message: str
    user_id: str = "anonymous"

class ChatResponse(BaseModel):
    response: str
    intent: str = "unknown"   # "general_query" | "order_query" | "ambiguous"

class LinkRequest(BaseModel):
    url: str

class IngestRequest(BaseModel):
    mode: str = "all"  # "all" | "recent"

@router.post("/chat", response_model=ChatResponse)
def api_chat(request: ChatRequest):
    try:
        result = chat_with_agent(request.message)
        return ChatResponse(response=result["response"], intent=result["intent"])
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/chat/stream")
async def api_chat_stream(request: ChatRequest):
    """
    Streaming chat endpoint using Server-Sent Events (SSE).
    The client receives tokens as they are generated by the LLM.

    Each SSE event payload is JSON:  {"token": str, "intent": str, "done": bool}
    When done=true the stream is complete.
    """
    return StreamingResponse(
        stream_chat_with_agent(request.message),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",  # disable nginx buffering if behind a proxy
        },
    )

@router.post("/upload")
def upload_file(file: UploadFile = File(...)):
    try:
        os.makedirs(DATA_DIR, exist_ok=True)
        file_path = os.path.join(DATA_DIR, file.filename)
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
        return {"message": f"Successfully uploaded {file.filename}"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/add-link")
def add_link(request: LinkRequest):
    try:
        tavily_api_key = os.getenv("TAVILY_API_KEY")
        if not tavily_api_key:
            raise HTTPException(status_code=500, detail="TAVILY_API_KEY environment variable is not set.")
            
        client = TavilyClient(api_key=tavily_api_key)
        print(f"Scraping URL: {request.url} via Tavily...")
        response = client.extract(urls=[request.url], extract_depth="advanced")
        results = response.get("results", [])
        if not results:
            raise HTTPException(status_code=400, detail="Failed to extract content from the URL.")
            
        content = results[0].get("raw_content", "")
        if not content:
            raise HTTPException(status_code=400, detail="No content extracted from the URL.")
            
        os.makedirs(DATA_DIR, exist_ok=True)
        parsed_url = urlparse(request.url)
        clean_netloc = parsed_url.netloc.replace(".", "_")
        filename = f"web_{clean_netloc}_{abs(hash(request.url)) % 10000}.txt"
        file_path = os.path.join(DATA_DIR, filename)
        
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
            
        return {"message": f"Successfully extracted content from {request.url} and saved as {filename}"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/ingest")
def trigger_ingest(request: IngestRequest = None):
    mode = (request.mode if request and request.mode in ("all", "recent") else "all")
    try:
        print(f"Starting document ingestion (mode={mode}) from endpoints...")
        index = run_ingestion_pipeline(data_dir=DATA_DIR, mode=mode)
        if index is None:
            return {"message": f"Ingestion ({mode}) completed, but no documents were found."}
        return {"message": f"Ingestion ({mode}) successfully completed! Vector index updated in Pinecone."}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/documents")
def list_documents():
    try:
        if not os.path.exists(DATA_DIR):
            return {"documents": []}
        files = os.listdir(DATA_DIR)
        doc_list = []
        for file in files:
            file_path = os.path.join(DATA_DIR, file)
            if os.path.isfile(file_path):
                stat = os.stat(file_path)
                doc_list.append({
                    "name": file,
                    "size": stat.st_size,
                    "modified": stat.st_mtime
                })
        return {"documents": doc_list}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.delete("/documents/{filename}")
def delete_document(filename: str):
    try:
        file_path = os.path.join(DATA_DIR, filename)
        if os.path.exists(file_path) and os.path.isfile(file_path):
            os.remove(file_path)
            return {"message": f"Successfully deleted {filename}"}
        else:
            raise HTTPException(status_code=404, detail="Document not found.")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
